### ISSUE TITLE
Don't open location list in landscape by default when there is only 1 location

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#1619]
### Discussed in https://github.com/breezy-weather/breezy-weather/discussions/1616

<div type='discussions-op-text'>

<sup>Originally posted by **mak7im01** February  5, 2025</sup>
</div>

Have the location list closed by default when the number of locations is strictly 1, and opened by default in other cases:
- 0 because when you have no location, this allows a quick access to "Add a location"
- 2+ because that helps switching easily between your saved locations

Take into account that the current approach used to automatically open the location list when the list is empty (first use of the app) cannot be used as is, because that would result in the location list automatically closing in the following case:
1. Add 2 locations
2. Remove 1 location
3. The location list closes itself

**Comment by DogacTanriverdi** [comment]
Hey @papjul. I think I've fixed the issue in #1633. Can you please review my PR? Since it is my first PR, I may have made mistakes in opening a PR or contributing to the code. I would be grateful if you can tell me where I went wrong or where I need to fix it.

**Comment by papjul** [comment]
> First example:
> 
>     1. The application is started in portrait mode
> 
>     2. The location list is opened
> 
>     3. Switch to landscape mode
> 
>     4. The location list remains open when the application is switched to landscape mode. (Regardless of the number of locations inside the location list.)

No, the location list is only opened in the following case: the location list is empty. This specific case is already implemented. In other cases, do nothing.

> Second example:
> 
>     1. The application is started in landscape mode or switched to landscape mode when in home screen (Location drawer is closed) and there is only 1 location in location list.
> 
>     2. The location list will not open.

No, there are many cases inside your example:
- If the device supports drawer (small and normal-sized phones don't support it), the drawer is open by default, so you have to close it. If you find a way to make it not open by default in this case (to avoid an unneeded 2-steps: 1. open the drawer > 2. close it right away), it's better, but it's not required.
- If the device doesn't support drawer, you do nothing

> Third example:
> 
>     1. The application is in landscape mode and there are 2 locations in the location list.
> 
>     2. (Location drawer is open) One of the locations is being deleted.
> 
>     3. The location drawer still remains open.
> 
>     4. But the application is switched to portrait mode and switched again to landscape mode, or the application is just started in landscape mode with 1 location, the location drawer will not open.

3. You do nothing, you don't force it to open
4. This one is confusing to me, there are too many cases in one, and one of them was already in the 2nd example.

Basically, all I'm asking is to implement this algorithm:
```
IF app was just started (not first time ever) AND location list size is strictly 1 AND isLandscape AND device has the layout with the drawer THEN
    Close the location drawer
ENDIF
```

If all conditions are matched, then you close the location drawer. Otherwise, you do nothing, and you don't touch other existing algorithms (such as the empty location list algorithm).

**Comment by DogacTanriverdi** [comment]
Okay. First of all, sorry it took me so long to understand the exact problem. I think i get it now. Here's what I understand:
    Only close (don't open it if possible) the drawer in landscape mode if app was just started (not first time ever) and it has strict 1 location. 

Just to be sure, last question: 
    With 1 location, when user switch from portrait mode to landscape mode, should the drawer be open by default (i.e. I won't change anything in the code) or closed?

**Comment by papjul** [comment]
> Here's what I understand: Only close (don't open it if possible) the drawer in landscape mode if app was just started (not first time ever) and it has strict 1 location.

You forgot the "device has the layout with the drawer" condition. The `setManagementFragmentVisibility` function applies to both the drawer and the separate screen. So, you must ensure you're using the layout with the drawer first.

> With 1 location, when user switch from portrait mode to landscape mode, should the drawer be open by default (i.e. I won't change anything in the code) or closed?

Good question! From the Android lifecycle point of view, when you change the orientation, the activity is recreated (`onCreate` is called again). So rather than "app was just started (first time ever or not)", it would be more correct to say to check the conditions "every time `MainActivity` is created" ;)

**Comment by DogacTanriverdi** [comment]
How does it look? Is there anything missing? Should I open a PR?

https://github.com/user-attachments/assets/3e7da124-bf50-45a3-bec5-8b04bdc1a14f

**Comment by papjul** [comment]
Yes, please open a PR with this change, and I will review it.

But first, please:
- run `./gradlew spotlessApply`, I see some lint issues.
- move your code between `initView()` and `consumeIntentAction(intent)`

Thanks!

**Comment by DogacTanriverdi** [comment]
I ran the `./gradlew spotlessApply` and get this:

- Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0. 
- 26 actionable tasks: 21 executed, 5 up-to-date

I moved my code between `initView()` and `consumeIntentAction(intent)` and it still works fine.

I opened a PR: #1636
