### ISSUE TITLE
Baidu location provider is not working

### ISSUE THREAD

**Issue by UjuiUjuMandan** [breezy-weather/breezy-weather#594]
### Steps to reproduce

1. Set location provider to Baidu
2. Scroll to refresh

### Expected behavior

Get current location 

### Actual behavior

App reports 'Failed to find current location'.

### Weather source used

中国

### Breezy Weather version

4.6.12-beta

### Android version

Android 14

### Device

Google Pixel 5

### Other details

Another questions.

1. I have seen 'Throw error when trying to locate outside China when using Baidu IP location, instead of positioning on 0, 0' in CHANGELOG.md, but on Baidu's website it says they support overseas locations: https://lbsyun.baidu.com/faq/api?title=android-locsdk . Anyway I am in China.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
There's no weather source called Baidu, Baidu IP location is a location source (helps finding position from your IP). This is a different product from Baidu location SDK. Here is the correct link: https://api.map.baidu.com/lbsapi/cloud/ip-location-api.htm

That being said, I no longer find any mention of being limited to mainland China, so please give us the weather source used for "current location". You can see it in location list.

Please also share your Debug > Crash log.

**Comment by papjul** [comment]
> If so, why would you 'Throw error when trying to locate outside China when using Baidu IP location, instead of positioning on 0, 0'?

Baidu IP location returns 0,0 position when they can't find us, instead of throwing an error. So it appears they located you in 0,0 so the weather for 0,0 would be shown, but it makes no sense, so now we detect when it's 0,0 and we throw an error in that case.

> Sorry, my mistake, I have corrected it to 中国.

There you have you reason. 中国 can't reverse geocode your location because it only supports mainland China. Please use a different source.

**Comment by UjuiUjuMandan** [comment]
@papjul 
> because it only supports mainland China

But.. I am in mainland China now.

I will attach a screen record for you better locate my issue.

(Uploading)

From the record you can see it's nothing related to weather provider, but to location one.

**Comment by UjuiUjuMandan** [comment]
BTW, when using IP.SB as location provider, I can clearly see such requests in my VPN client's log, as I scroll to refresh location:

```
[TCP] 172.19.0.1:48302(org.breezyweather) --> api.ip.sb:443 match DomainSuffix(ip.sb) using DIRECT
```

However, when using Baidu one, there's no requests related to Baidu, etc.

**Comment by papjul** [comment]
Ah yes, my bad, since you quoted the changelog related to the "outside China" error, I thought that was your case. I will try to reproduce.

**Comment by UjuiUjuMandan** [comment]
What API key are you using, the original GeometricWeather's or registered one on yourself?

**Comment by papjul** [comment]
Yes, I use that one, as it's unclear to me how to register for a new one; it seems they want my phone number or download some app in Chinese :(

**Comment by UjuiUjuMandan** [comment]
How can I get the more detailed log of BreezyWeather? I want to find the response status code from Baidu to determine if it's the key has reached limit or expired.

**Comment by UjuiUjuMandan** [comment]
> it seems they want my phone number or download some app in Chinese (which I don't speak) :(

That's the last step facial recognition, which they suggest to use Baidu app to scan the code, but their app is buggy and constantly and wrongly saying camera permission is not granted, finally I use WeChat to scan it and passed the recognition. They tell me to wait for response in 3 work days.

Since they ask for Chinese ID number, I don't think any foreigner can get an API key.

**Comment by papjul** [comment]
Daily limit has been reached for Baidu IP location. But regardless of that, it wasn't working for quite a few versions due to some mistake I made when refactoring the code. You can input Geometric Weather key manually to workaround the issue, although currently, app doesn't tell you when limit is reached.

**Comment by UjuiUjuMandan** [comment]
> You can input Geometric Weather key manually to workaround the issue,

It's correct if you say input my own key to workaround, don't you use same key of GW by default?

**Comment by papjul** [comment]
No, I said "input Geometric Weather key", or just wait for next version where you don't need to do anything.
The issue I fixed was that the app was only taking manually added keys and ignoring the bundled key (which is the same as the one used in Geometric Weather).

**Comment by UjuiUjuMandan** [comment]
I don't need to do anything, really? Isn't the "Daily limit has been reached for Baidu IP location"?

**Comment by papjul** [comment]
Daily limit will be reset tomorrow so you will be able to use it tomorrow… but yeah, I understand what you mean, limit will be reached again tomorrow after some time, so if you can register your own key, it's probably better.

**Comment by papjul** [comment]
> It's definitely not in source code repository

Unfortunately, it is, in Gradle properties, that's what allowed me to easily reuse them.

Breezy Weather now uses private variables from GitHub.

**Comment by UjuiUjuMandan** [comment]
@papjul I have got my own API key and successfully queried location through `http://api.map.baidu.com/location/ip?ak=123456789`

But remember what I said?

> However, when using Baidu one, there's no requests related to Baidu, etc.

I inputed this key in App, the location still fails, and there's no network activity to Baidu, too.

I can email the key to you for debugging purpose.
